print("Viết ngắn gọn các lệnh:")
print("(a) x += 1")
print("(b) x /= 2")
print("(c) x -= 1")
print("(d) x += y")
print("(e) x -= (y + 7)")
print("(f) x *= 2")
print("(g) number_of_closed_cases += 2 * ncc")
